services:
  # The Web Server (PHP + Apache)
  web:
    container_name: simplifythem-web  # UNIQUE NAME
    build: .
    ports:
      - "8001:80"  # UNIQUE PORT
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  # The Database
  database:
    container_name: simplifythem-db   # UNIQUE NAME
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simplifythem_db  # YOUR DB NAME 
    ports:
      - "3309:3306" # Use a different port
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: